# Generated by Django 6.0.4 on 2026-04-24 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('snapshot_date', models.DateField()),
                ('subscriber_count', models.BigIntegerField(default=0)),
                ('view_count', models.BigIntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('subscriber_delta', models.IntegerField(default=0)),
                ('view_delta', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['user', 'snapshot_date'], name='channel_sna_user_id_a9144e_idx')],
                'unique_together': {('user', 'channel_id', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='VideoMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('avg_view_duration', models.FloatField(default=0)),
                ('click_through_rate', models.FloatField(default=0)),
                ('impressions', models.BigIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_metrics',
                'ordering': ['-published_at'],
                'unique_together': {('user', 'video_id')},
            },
        ),
    ]
